version: "3.7"

services:
  redis:
    image: redis:6.2
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_DB: turk
      POSTGRES_USER: turk
      POSTGRES_PASSWORD: turk
    volumes:
      - db:/var/lib/postgresql/data:rw
    shm_size: 1g
  db:
    image: toloco/pgbouncer:1.16
    environment:
      DB_HOST: postgres
      DB_USER: turk
      DB_PASSWORD: turk
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "6432:6432"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${_TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${_TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"

volumes:
  db: { }
  redis: { }
