# Generated by Django 4.0.3 on 2022-05-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PollStats',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_attempts', models.IntegerField(blank=True, default=0)),
                ('correct_answers', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('cheer_up', 'Cheer Up')], max_length=32)),
                ('content', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.language')),
            ],
        ),
    ]
