# Generated by Django 4.0.3 on 2022-05-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [ ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='words.language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='words.word')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='words.word')),
            ],
        ),
    ]
