# Generated by Django 4.0.3 on 2022-05-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20220512_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('content', models.CharField(max_length=512)),
                (
                    'word', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='words.word',
                    ),
                ),
            ],
        ),
    ]
